"""
Django settings for reduxProj project.

Generated by 'django-admin startproject' using Django 1.11.12.

For more information on this file, see
https://docs.djangoproject.com/en/1.11/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.11/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.11/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '^^vfj%y)%#@hv#&h^m43ltqzw-3blx4i8=**-3^d^x-xf4&x9&'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

#Email sending settings
EMAIL_HOST = 'smtp.mail.ru'
EMAIL_PORT = 2525
EMAIL_HOST_USER = "kulebyaka2020@mail.ru"
EMAIL_HOST_PASSWORD = "Test2018!"
EMAIL_USE_TLS = True

#Add next two lines to enable sending traceback emails to admins
SERVER_EMAIL = 'kulebyaka2020@mail.ru'          #must be the same as EMAIL_HOST_USER
DEFAULT_FROM_EMAIL = 'kulebyaka2020@mail.ru'

'''
Отправить сообщение
Чтобы послать письмо нужно лишь в коде вызвать команду send_mail, например

from django.conf import settings
send_mail('Тема', 'Тело письма', settings.EMAIL_HOST_USER, ['to@example.com'])
Обратите внимание, что для предотвращения ошибки 
501 sender address must match authenticated user 
нужно использовать адрес отправителя такой же, 
как EMAIL_HOST_USER (адрес пользователя при подключении к SMPT серверу).
Более подробно об этой ошибки в статье:
Error: SMTPRecipientsRefused 501 - sender address must match authenticated user
'''

# During development we will use console email backend
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
#EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend' < default


# Application definition

INSTALLED_APPS = [
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sites',
    'registration',
    'django.contrib.admin',
    'landing.apps.LandingConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'reduxProj.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            '/home/user/work/reduxProj/templates/',
            # '',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'reduxProj.wsgi.application'


# Database
# https://docs.djangoproject.com/en/1.11/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}


# Password validation
# https://docs.djangoproject.com/en/1.11/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/1.11/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.11/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_FINDERS = [
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
]

# Your project will probably also have static assets that
# aren’t tied to a particular app.
# In addition to using a static/ directory inside your apps,
# you can define a list of directories (STATICFILES_DIRS) in
# your settings file where Django will also look for static files.
# For example:

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    # '/home/user/work',
]
print(STATICFILES_DIRS)
# DJANGO REGISTRATION REDUX SETTINGS
ACCOUNT_ACTIVATION_DAYS = 7         # One-week activation window
REGISTRATION_AUTO_LOGIN = True      # Automatically log the user in.
SITE_ID = 1
LOGIN_REDIRECT_URL = '/landing'
